# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/cli"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/dart-generator"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/node-runtime"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/playground"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/typescript-generator"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/browser-runtime"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/csharp-generator"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/kotlin-generator"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/parser"
    schedule:
      interval: "daily"
