stages:
  - build
  - deploy

build:
  stage: build
  image: node
  only:
    - master
  script:
    - yarn
    - NODE_ENV=production npx webpack --config webpack.config.js
    # - npx webpack --config webpack.config.js
  artifacts:
    paths:
      - dist/


deploy:
  stage: deploy
  image: node
  only:
    - master
  script:
    - npm install netlify-cli -g
    - cp _redirects dist/_redirects
    - netlify deploy --dir dist/ -s $NETLIFY_SITE_ID --prod
