image: node
stages:
  - setup
  - typecheck
  - test
  - build
  - deploy
variables:
  DOCKER_DRIVER: overlay2

setup:
  stage: setup
  script:
    - yarn
  artifacts:
    paths:
      - node_modules/
    expire_in: '2h'

typecheck: 
  stage: typecheck
  script:
    - yarn run check

test: 
  stage: test
  script:
    - yarn test

build:
  stage: build
  only:
    - master
  script:
    - NODE_ENV=production npx webpack --config webpack.config.js
  artifacts:
    paths:
      - dist/


deploy:
  stage: deploy
  only:
    - master
  script:
    - npm install netlify-cli -g
    - cp _redirects dist/_redirects
    - netlify deploy --dir dist/ -s $NETLIFY_SITE_ID --prod
