language: node_js
node_js:
- '8'
- '10'
- '12'
deploy:
  skip_cleanup: true
  provider: npm
  email: guilherme@cubos.io
  api_key:
    secure: aK0gOwVv8e2/Gur/k/AKyXTtLLbUZApi1nui0IoUkGlBohVjf7IXJejzKOzUqCyIr14/0ve2Ba1x5rMZ0KHpCPMakY7764XEeqY38iuQaL1mnDwCKvFQkYUT/Qh/5te0CD0lHMmuNmNJu3ROQqL4eQSZ2Trw67jFuF626G24ie5EXC1xhC/MJ98MzVmhv+t3wj8ifbO2R8rLxs18em2wNtLWC8ZFKbow0vU/fj5l41P6PUZ/cDUBvrd3vYTVZ3QRukJ21mMu1c0+l2i3w9fXyUgXAiB8zhuzTujlH4TfVTEQUinAjtgramuBsLGKNeif/DnZKGrZp/7qCnMlvB1JzYw3Pab9AOqkAWGizfUv/vDWqo12Co8MTjjPCzeTN0XiiK0A0X23lU7MAIARtuGHnOlbd8PbfRaxDcdJu5B4JSQ2+QjCl3IlVkF+bkXN3XkO2NXa7sJ2biXusv3gsDV8apvbUAVjNfG0gtqGgqOOZTLnuIWmJwavXwn46j7abgP1PRPp+tLYhYU4SfoSp/9PbjMcsA7qT2dVJk7lWOA036Y4IAeeojNhUzjkRHQ0L9q8A+DlhS34IL1vuqOm3bJ/X+Dq8GGmj5kMIJ61K3ZL/wD3Wom57OwgrN0ROP9K6Cp/QDswC8xAJLWPTzMMUyMS8sLsa691Hxf/k4szEeM/7dI=
  on:
    tags: true
    repo: sdkgen/node-runtime
