language: dart
dart:
- stable
- dev
install:
- pub get
script:
- dartanalyzer .
- dartfmt -n --fix .
deploy:
  provider: script
  script:
  - mkdir -p ~/.pub-cache
  - echo $PUB_CREDENTIALS > ~/.pub-cache/credentials.json
  - pub publish -f
  on:
    tags: true