language: dart
dart:
- stable
- dev
install:
- pub get
script:
- dartanalyzer .
- dartfmt -n --fix .
deploy:
  provider: script
  script: "bash -c 'mkdir -p ~/.pub-cache; echo $PUB_CREDENTIALS | base64 -d > ~/.pub-cache/credentials.json; pub publish -f || true'"
  on:
    tags: true