os:
  - linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid-fallback
before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor
script:
- ./flutter/bin/flutter pub get
- ./flutter/bin/flutter dartanalyzer .
- ./flutter/bin/flutter dartfmt -n --fix .
deploy:
  provider: script
  script: "bash -c 'mkdir -p ~/.pub-cache; echo $PUB_CREDENTIALS | base64 -d > ~/.pub-cache/credentials.json; ./flutter/bin/flutter pub publish -f || true'"
  on:
    tags: true