os:
  - linux
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid-fallback
before_script:

  - git clone https://github.com/flutter/flutter.git -b stable ../flutter
  - ../flutter/bin/flutter doctor
script:
- ../flutter/bin/flutter pub get
# - ../flutter/bin/flutter dartanalyzer .
# - ../flutter/bin/flutter dartfmt -n --fix .
deploy:
  provider: script
  script: "bash -c 'mkdir -p ~/.pub-cache; echo $PUB_CREDENTIALS | base64 -d > ~/.pub-cache/credentials.json; ../flutter/bin/flutter pub publish || true'"
  on:
    tags: true