language: node_js
node_js:
- '8'
- '10'
- '12'
deploy:
  skip_cleanup: true
  provider: npm
  email: guilherme@cubos.io
  api_key:
    secure: PnPbqOWt5u4e0vN6Kx1i4b0DaI8w1tfw6dTJ0jgbnw5JWrQG4qKaGAwq9nECP/Njqo1aNyxq4vsk0Wpa15ALTQX7YVoCoPBIBXsOBogssIqZm8ez/nl5fi37w3kZayyE0ikXPw+9Ipd8Jih84e+mxN1HmYd5Qth325Iixk3VhATDbUIhi9ngEfD5rDPraq6oA6qOjNThiUXVMJ0G/DAhs+Kxx39MGKsImeCl6DxYuOTCy7SanLYRv3DjLipRhAJd0LzpDbUOvaZBBXPdHo5N+uU1VAfgM6YqvgvYkW58mfnOCcbcUWrje674AtZDpD0+5WIxo+OAP6M5uM4dm+RAqFYIw/MIXJ8+wXzu0oiRwcAaDFh07jY3lpTb1sMY0W4b1pyd7Qt5ZBYLenlva+61y6b+5bdngt15cIe1r/pzBQmWc2Qrtslp0ocNZ5HXV/E9ThmR/ExEbbc5zgtokmxwszrTcaGGqRMu9WRGzTjAUqfxGrxX95V/Z2TDJatDvetdTQyoRt2pG844KPaKE3CYKiV2JwVlhRJ5ZfmxecNXFWAB3uBGMrh96P1WKg98w0V1Ld8YpvWGblKaNOmlz2ZLH5/cn/v7cDncuRaPZaKntO5pgI4yZX/lC7U8KRxMO0xd4nAK0KCDCuiz+s/GExpFu3PP4vry4BMgR9AaXAMm4vQ=
  on:
    tags: true
    repo: sdkgen/browser-runtime
