site_name: sdkgen
site_url: https://sdkgen.github.io
repo_url: https://github.com/sdkgen/sdkgen
plugins:
  - search:
      lang: [pt]
theme:
  language: pt
  name: material
  features:
    - navigation.instant
    - toc.autohide
  palette:
    primary: deep purple
  logo: logo.png
  favicon: logo.png
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/sdkgen
      name: Telegram
    - icon: fontawesome/brands/github
      link: https://github.com/sdkgen/sdkgen
      name: GitHub
nav:
  - index.md
  - primeiro-projeto.md
  - descrevendo-api.md
