name: sdkgen_runtime
version: 1.0.6
author: Cubos <tech@cubos.io>
homepage: https://github.com/sdkgen/dart-runtime
description: Dart API client for sdkgen server. It must be used with a generated file, see docs.

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ^0.12.0
  convert: ^2.1.1
