name: sdkgen_runtime
version: 1.0.11
author: Cubos <tech@cubos.io>
homepage: https://github.com/sdkgen/dart-runtime
description: Dart API client for sdkgen server. It must be used with a generated file, see docs.

environment:
  sdk: '>=2.1.0 <3.0.0'
  flutter: ">=1.5.0 <2.0.0"

dependencies:
  http: ^0.12.0+2
  convert: ^2.1.1
  shared_preferences: ^0.5.6
  get_version: 0.2.0+1
  device_info: 0.4.1+4
  flutter:
    sdk: flutter
