name: sdkgen_runtime
version: 0.0.0
homepage: https://github.com/sdkgen/sdkgen
description: Dart API client for sdkgen server. It must be used with a generated file, see docs.

environment:
  sdk: '>=2.1.0 <3.0.0'
  flutter: ">=1.5.0 <2.0.0"

dependencies:
  http: ^0.12.0+4
  convert: ^2.1.1
  shared_preferences: ^0.5.6+1
  get_version: ^0.2.1
  device_info: ^0.4.1+4
  flutter:
    sdk: flutter
