name: sdkgen_runtime
version: 0.0.0
homepage: https://github.com/sdkgen/sdkgen
description: Dart API client for sdkgen server. It must be used with a generated file, see docs.

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.5.0 <2.0.0"

dependencies:
  http: ^0.12.2
  convert: ^2.1.1
  shared_preferences: ^0.5.12+2
  package_info: ^0.4.3
  device_info: ^0.4.2+9
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.15.4
  flutter_test:
    sdk: flutter
