name: release
on:
  release:
    types: [published]
jobs:

  parser:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        registry-url: https://registry.npmjs.org
    - run: |
        npm install -g json && json -I -f package.json -e '
          this.version = "${{ github.ref }}".replace("refs/tags/", "");
          this.main = "dist/src/index.js";
          this.types = "dist/src/index.d.ts";
          for (const pkg in this.dependencies)
            if (this.dependencies[pkg].startsWith("file:../"))
              this.dependencies[pkg] = this.version;
        '
      working-directory: ./parser
    - run: npm install
      working-directory: ./parser
    - run: npm publish
      working-directory: ./parser
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
