name: test
on: [push, pull_request]
jobs:
  browser-runtime:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx lerna bootstrap
      - run: npm run eslint:check
        working-directory: ./packages/browser-runtime
      - run: npm run build
        working-directory: ./packages/browser-runtime
      - run: npm test
        working-directory: ./packages/browser-runtime

  cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx lerna bootstrap
      - run: npm run eslint:check
        working-directory: ./packages/cli
      - run: npm run build
        working-directory: ./packages/cli
      - run: npm test
        working-directory: ./packages/cli

  dart-generator:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx lerna bootstrap
      - run: npm run eslint:check
        working-directory: ./packages/dart-generator
      - run: npm run build
        working-directory: ./packages/dart-generator
      - run: npm test
        working-directory: ./packages/dart-generator

  dart-runtime:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter-version: [2.0.x, 2.2.x, 2.5.x]
        flutter-channel: [stable]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ matrix.flutter-version }}
          channel: ${{ matrix.flutter-channel }}
      - run: flutter pub get
        working-directory: ./packages/dart-runtime
      - run: flutter test
        working-directory: ./packages/dart-runtime
      - run: if [ "${{ matrix.flutter-version }}" == "2.5.x" ]; then flutter analyze; fi
        working-directory: ./packages/dart-runtime
      - run: if [ "${{ matrix.flutter-version }}" == "2.5.x" ]; then flutter format . --set-exit-if-changed; fi
        working-directory: ./packages/dart-runtime
      - run: if [ "${{ matrix.flutter-version }}" == "2.5.x" ]; then flutter pub pub publish --dry-run; fi
        working-directory: ./packages/dart-runtime

  node-runtime:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx lerna bootstrap
      - run: npm run eslint:check
        working-directory: ./packages/node-runtime
      - run: npm run build
        working-directory: ./packages/node-runtime
      - run: npm test
        working-directory: ./packages/node-runtime

  parser:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx lerna bootstrap
      - run: npm run eslint:check
        working-directory: ./packages/parser
      - run: npm run build
        working-directory: ./packages/parser
      - run: npm test
        working-directory: ./packages/parser

  playground:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx lerna bootstrap
      - run: npm install -g json && bash .ci.sh
        working-directory: ./packages/playground
      - run: npm run eslint:check
        working-directory: ./packages/playground
      - run: npm run build
        working-directory: ./packages/playground

  typescript-generator:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx lerna bootstrap
      - run: npm run eslint:check
        working-directory: ./packages/typescript-generator
      - run: npm run build
        working-directory: ./packages/typescript-generator
      - run: npm test
        working-directory: ./packages/typescript-generator

  csharp-generator:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx lerna bootstrap
      - run: npm run eslint:check
        working-directory: ./packages/csharp-generator
      - run: npm run build
        working-directory: ./packages/csharp-generator
      - run: npm test
        working-directory: ./packages/csharp-generator

  dotnet-runtime:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["3.1.x", "5.0.x", "6.0.x"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          include-prerelease: true
      - run: dotnet pack
        working-directory: ./packages/dotnet-runtime

  kotlin-generator:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx lerna bootstrap
      - run: npm run eslint:check
        working-directory: ./packages/kotlin-generator
      - run: npm run build
        working-directory: ./packages/kotlin-generator
      - run: npm test
        working-directory: ./packages/kotlin-generator

  swift-generator:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx lerna bootstrap
      - run: npm run eslint:check
        working-directory: ./packages/swift-generator
      - run: npm run build
        working-directory: ./packages/swift-generator
      - run: npm test
        working-directory: ./packages/swift-generator

  android-runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: giorgosneokleous93/docker-multicommand-android@v1.0.0
        with:
          workingdir: "./packages/android-runtime/"
          command1: "./gradlew test assembleRelease"

  vscode-ext:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g vsce
      - run: vsce package
        working-directory: ./vscode-ext
